In [15]:
import numpy as np

In [16]:
a=np.array([1.0,2,3,1,0],dtype=np.int16)
a

array([1, 2, 3, 1, 0], dtype=int16)

In [17]:
type(a)

numpy.ndarray

In [18]:
a.dtype

dtype('int16')

In [19]:
print(a)
print(f'{a.shape=}')
print(f'{a.ndim=}')
print(f'{a.size=}')
print(f'{a.dtype}')
print(f'{a.itemsize=}')
print(f'{a[0]=}')

[1 2 3 1 0]
a.shape=(5,)
a.ndim=1
a.size=5
int16
a.itemsize=2
a[0]=np.int16(1)


In [20]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [21]:
b=np.array([[1,8,3],[3,2,3]
            ,[3,5,6]])


In [22]:
print(b)
print(f'{b.shape=}')
print(f'{b.ndim=}')
print(f'{b.size=}')
print( f'{b.dtype}')
print(f'Размер каждого элемента в байтах {b.itemsize=}')
print(f'Нулевая страна {b[0]=}')
print(f'Элемент из первой строки и второго столбца {b[0,1]=}')
print(f'Элемент из второй строки и третьего столбца {b[1,2]=}')


[[1 8 3]
 [3 2 3]
 [3 5 6]]
b.shape=(3, 3)
b.ndim=2
b.size=9
int64
Размер каждого элемента в байтах b.itemsize=8
Нулевая страна b[0]=array([1, 8, 3])
Элемент из первой строки и второго столбца b[0,1]=np.int64(8)
Элемент из второй строки и третьего столбца b[1,2]=np.int64(3)


In [23]:
a[3]=-84
a

array([  1,   2,   3, -84,   0], dtype=int16)

In [24]:
np.array([[1,8,3],[3,2,3],5,'string'],dtype=object)

array([list([1, 8, 3]), list([3, 2, 3]), 5, 'string'], dtype=object)

### **Способы генерации массиивов**

### **Заполненный нулями**

In [26]:
m=np.zeros((4,3))
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
m.ndim

2

In [28]:
m=np.zeros(((4,3,2)))
m

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [30]:
m.ndim

3

In [31]:
b

array([[1, 8, 3],
       [3, 2, 3],
       [3, 5, 6]])

In [32]:
m=np.zeros_like(b)
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
m=np.ones((5,4))
m

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
m.shape

(5, 4)

In [35]:
m=np.ones_like(b)
m

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
m=np.eye(13)
m

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.eye(3,5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [40]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [44]:
m=np.linspace(0,3,4)
m

array([0., 1., 2., 3.])

In [45]:
m.dtype

dtype('float64')

In [47]:
np.linspace(0,3)

array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ])

In [48]:
np.linspace(0,3,dtype=np.float16)

array([0.     , 0.06122, 0.12244, 0.1837 , 0.2449 , 0.3062 , 0.3674 ,
       0.4285 , 0.4897 , 0.551  , 0.6123 , 0.6733 , 0.735  , 0.796  ,
       0.857  , 0.9185 , 0.9795 , 1.041  , 1.102  , 1.163  , 1.225  ,
       1.286  , 1.347  , 1.408  , 1.47   , 1.53   , 1.592  , 1.653  ,
       1.714  , 1.775  , 1.837  , 1.898  , 1.959  , 2.02   , 2.082  ,
       2.143  , 2.203  , 2.266  , 2.326  , 2.389  , 2.45   , 2.51   ,
       2.572  , 2.633  , 2.693  , 2.756  , 2.816  , 2.877  , 2.94   ,
       3.     ], dtype=float16)

In [50]:
np.linspace??

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x112aba5c0>
File:            /opt/anaconda3/envs/kurs/lib/python3.12/site-packages/numpy/_core/function_base.py
Source:         
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0, *, device=None):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linsp

### Помимо линейного, можно задать еще и экспоненциальный диапозон

In [51]:
start, end=1,4
np.logspace(start,end,num=50,base=10)


array([   10.        ,    11.51395399,    13.25711366,    15.26417967,
          17.57510625,    20.23589648,    23.29951811,    26.82695795,
          30.88843596,    35.56480306,    40.94915062,    47.14866363,
          54.28675439,    62.50551925,    71.9685673 ,    82.86427729,
          95.40954763,   109.8541142 ,   126.48552169,   145.63484775,
         167.68329368,   193.06977289,   222.29964825,   255.95479227,
         294.70517026,   339.32217719,   390.69399371,   449.8432669 ,
         517.94746792,   596.36233166,   686.648845  ,   790.60432109,
         910.29817799,  1048.11313415,  1206.79264064,  1389.49549437,
        1599.85871961,  1842.06996933,  2120.95088792,  2442.05309455,
        2811.76869797,  3237.45754282,  3727.59372031,  4291.93426013,
        4941.71336132,  5689.86602902,  6551.2855686 ,  7543.12006335,
        8685.11373751, 10000.        ])

In [53]:
np.logspace(2.0,5.0,num=4,base=2)

array([ 4.,  8., 16., 32.])

### Равномерное распределение 

In [ ]:
np.random.seed(42)  # Установка зерна для воспроизводимости


In [54]:
print(np.random.rand(3,4))  # 3x4 массив случайных чисел от 0 до 1


[[0.31822971 0.64287036 0.13523635 0.73820269]
 [0.65536096 0.29795454 0.25917324 0.96904674]
 [0.13703137 0.01995453 0.85805684 0.85643221]]


### Нормальное распределение 

In [55]:
np.random.randn(2,3,2)  # 2x3x2 массив из стандартного нормального распределения

array([[[-0.59949223,  1.30825918],
        [-1.39845825,  0.01497311],
        [-1.01987335, -1.62862204]],

       [[-0.0554113 , -0.26170618],
        [-0.6368933 ,  0.35272771],
        [-1.52493496,  1.91148815]]])